version: '2.1'

services:
  app:
    build: .
    #volumes:
    #  - .:/app
    ports:
    - "8080:8080"
    depends_on:
        db:
          condition: service_healthy
    links:
      - db
    env_file:
    - core.env
    entrypoint: ["/bin/sh", "entrypoint.sh"]

  db:
    image: postgres:10.2
    volumes:
      - postgres_data:/var/lib/postgresl/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    env_file:
    - core.env

  # running on a single node for development.
  # prod settings here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  postgres_data:
  es_data: